# Generated by Django 4.2.4 on 2023-08-18 10:59

import August_2023_Retake_Eventer.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[August_2023_Retake_Eventer.accounts.validators.first_name_only_letter], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=45)),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
                ('password', models.CharField(max_length=20, validators=[August_2023_Retake_Eventer.accounts.validators.password_should_have_at_least_one_digit], verbose_name=django.core.validators.MinLengthValidator(5))),
            ],
        ),
    ]
