# Generated by Django 4.2.4 on 2023-08-18 11:28

import August_2023_Retake_Eventer.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), August_2023_Retake_Eventer.accounts.validators.password_should_have_at_least_one_digit]),
        ),
    ]
