# Generated by Django 4.2 on 2023-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sports Car', 'Sports Car'), ('pickup', 'Pickup'), ('crossover', 'Crossover'), ('minibus', 'Minibus'), ('other', 'Other')], max_length=10),
        ),
    ]
