# Generated by Django 4.2.2 on 2023-06-20 09:42

import December_21_2022.plants.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), December_21_2022.plants.validators.name_validation]),
        ),
    ]
